=== Lixtec/lixbox-io/lixbox-edi/src/main/resources/fr/lixbox/io/edi/config.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="attributs">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="attribut" type="attribut" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="balises">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="balise" type="balise" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="edi-config">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="attributs"/>
        <xs:element ref="balises"/>
        <xs:element ref="schemas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="schemas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="schema" type="schema" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:complexType name="attr-ref">
    <xs:attribute name="code" type="xs:string" use="required"/>
    <xs:attribute name="isOblig" type="xs:boolean" use="required"/>
  </xs:complexType>
  <xs:complexType name="element">
    <xs:sequence>
      <xs:element name="attr-ref" type="attr-ref" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="code" type="xs:string"/>
    <xs:attribute name="name" type="xs:string"/>
    <xs:attribute name="isOblig" type="xs:boolean"/>
    <xs:attribute name="occurence" type="xs:int"/>
    <xs:attribute name="att-ref" type="xs:string"/>
  </xs:complexType>
  <xs:complexType name="balise">
    <xs:sequence>
      <xs:element name="element" type="element" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="nom" type="xs:string" use="required"/>
  </xs:complexType>
  <xs:complexType name="attribut">
    <xs:attribute name="code" type="xs:string" use="required"/>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="type" type="xs:string" use="required"/>
    <xs:attribute name="size" type="xs:int" use="required"/>
  </xs:complexType>
  <xs:complexType name="segGroupDesc">
    <xs:sequence>
      <xs:element name="segGroupDesc" type="segGroupDesc" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
    <xs:attribute name="initBalise" type="xs:string" use="required"/>
    <xs:attribute name="occurence" type="xs:int" use="required"/>
  </xs:complexType>
  <xs:complexType name="schema">
    <xs:sequence>
      <xs:element name="segGroupDesc" type="segGroupDesc" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="code" type="xs:string" use="required"/>
    <xs:attribute name="nom" type="xs:string" use="required"/>
    <xs:attribute name="version" type="xs:string" use="required"/>
  </xs:complexType>
</xs:schema>

=== Lixtec/lixbox-io/lixbox-edi/src/main/resources/fr/lixbox/io/edi/config.xml
<edi-config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="./config.xsd">
  <attributs>
    <attribut code="0001" name="Syntax identifier" type="AN" size="4"/>
    <attribut code="0002" name="Syntax version number" type="AN" size="1"/>
    <attribut code="0004" name="Interchange sender identification" type="AN" size="35"/>
    <attribut code="0007" name="Identification code qualifier" type="AN" size="4"/>
    <attribut code="0008" name="Interchange sender internal identification" type="AN" size="35"/>
    <attribut code="0010" name="Interchange recipient identification" type="AN" size="35"/>
    <attribut code="0014" name="Interchange recipient internal identification" type="AN" size="35"/>
    <attribut code="0017" name="Date" type="N" size="8"/>
    <attribut code="0019" name="Time" type="N" size="4"/>
    <attribut code="0020" name="Interchange control reference" type="AN" size="14"/>
    <attribut code="0022" name="Recipient reference/password" type="AN" size="14"/>
    <attribut code="0025" name="Recipient reference/password qualifier" type="AN" size="2"/>
    <attribut code="0026" name="Application reference" type="AN" size="14"/>
    <attribut code="0029" name="Processing priority code" type="AN" size="1"/>
    <attribut code="0031" name="Acknowledgement request" type="N" size="1"/>
    <attribut code="0032" name="Interchange agreement identifier" type="AN" size="35"/>
    <attribut code="0035" name="Test indicator" type="N" size="1"/>
    <attribut code="0036" name="Interchange control count" type="N" size="6"/>
    <attribut code="0042" name="Interchange sender internal sub-identification" type="AN" size="35"/>
    <attribut code="0046" name="Interchange recipient internal sub-identification" type="AN" size="35"/>
    <attribut code="0051" name="Controlling agency, coded" type="AN" size="3"/>
    <attribut code="0052" name="Message version number" type="AN" size="3"/>
    <attribut code="0054" name="Message release number" type="AN" size="3"/>
    <attribut code="0057" name="Association assigned code" type="AN" size="6"/>
    <attribut code="0062" name="Message reference number" type="AN" size="14"/>
    <attribut code="0065" name="Message type" type="AN" size="6"/>
    <attribut code="0068" name="Common access reference" type="AN" size="35"/>
    <attribut code="0070" name="Sequence of transfers" type="N" size="2"/>
    <attribut code="0073" name="First and last transfer" type="AN" size="1"/>
    <attribut code="0074" name="Number of segments in a message" type="N" size="10"/>
    <attribut code="0080" name="Service code list directory version number" type="AN" size="6"/>
    <attribut code="0110" name="Code list directory version number" type="AN" size="6"/>
    <attribut code="0113" name="Message type sub-function identification" type="AN" size="6"/>
    <attribut code="0115" name="Message subset identification" type="AN" size="14"/>
    <attribut code="0116" name="Message subset version number" type="AN" size="3"/>
    <attribut code="0118" name="Message subset release number" type="AN" size="3"/>
    <attribut code="0121" name="Message implementation guideline identification" type="AN" size="14"/>
    <attribut code="0122" name="Message implementation guideline version number" type="AN" size="3"/>
    <attribut code="0124" name="Message implementation guideline release number" type="AN" size="3"/>
    <attribut code="0127" name="Scenario identification" type="AN" size="14"/>
    <attribut code="0128" name="Scenario version number" type="AN" size="3"/>
    <attribut code="0130" name="Scenario release number" type="AN" size="3"/>
    <attribut code="0133" name="Character encoding, coded" type="AN" size="3"/>
    <attribut code="1000" name="Document name" type="AN" size="35"/>
    <attribut code="1001" name="Document name code" type="AN" size="3"/>
    <attribut code="1004" name="Document identifier" type="AN" size="35"/>
    <attribut code="1056" name="Version identifier" type="AN" size="9"/>
    <attribut code="1060" name="Revision identifier" type="AN" size="6"/>
    <attribut code="1131" name="Code list identification code" type="AN" size="17"/>
    <attribut code="1153" name="Reference code qualifier" type="AN" size="3"/>
    <attribut code="1154" name="Reference identifier" type="AN" size="70"/>
    <attribut code="1156" name="Document line identifier" type="AN" size="6"/>
    <attribut code="1225" name="Message function code" type="AN" size="3"/>
    <attribut code="1312" name="Code list responsible agency code" type="N" size="4"/>
    <attribut code="1366" name="Document source description" type="AN" size="70"/>
    <attribut code="1373" name="Document status code" type="AN" size="3"/>
    <attribut code="1490" name="Consolidation item number" type="N" size="4"/>
    <attribut code="1496" name="Goods item number" type="N" size="5"/>
    <attribut code="2005" name="Date or time or period function code qualifier" type="AN" size="3"/>
    <attribut code="2379" name="Date or time or period format code" type="AN" size="3"/>
    <attribut code="2380" name="Date or time or period text" type="AN" size="35"/>
    <attribut code="3035" name="Party function code qualifier" type="AN" size="3"/>
    <attribut code="3036" name="Party name" type="AN" size="35"/>
    <attribut code="3039" name="Party identifier" type="AN" size="35"/>
    <attribut code="3042" name="Street and number or post office box identifier" type="AN" size="35"/>
    <attribut code="3045" name="Party name format code" type="AN" size="3"/>
    <attribut code="3055" name="Code list responsible agency code" type="AN" size="3"/>
    <attribut code="3124" name="Name and address description" type="AN" size="35"/>
    <attribut code="3127" name="Carrier identifier" type="AN" size="17"/>
    <attribut code="3128" name="Carrier name" type="AN" size="35"/>
    <attribut code="3139" name="Contact function code" type="AN" size="3"/>
    <attribut code="3148" name="Communication address identifier" type="AN" size="512"/>
    <attribut code="3155" name="Communication address code qualifier" type="AN" size="3"/>
    <attribut code="3164" name="City name" type="AN" size="35"/>
    <attribut code="3207" name="Country name code" type="AN" size="3"/>
    <attribut code="3222" name="First related location name" type="AN" size="70"/>
    <attribut code="3223" name="First related location name code" type="AN" size="25"/>
    <attribut code="3224" name="Location name" type="AN" size="256"/>
    <attribut code="3225" name="Location name code" type="AN" size="35"/>
    <attribut code="3227" name="Location function code qualifier" type="AN" size="3"/>
    <attribut code="3228" name="Country sub-entity name" type="AN" size="70"/>
    <attribut code="3229" name="Country sub-entity name code" type="AN" size="9"/>
    <attribut code="3232" name="Second related location name" type="AN" size="70"/>
    <attribut code="3233" name="Second related location name code" type="AN" size="25"/>
    <attribut code="3251" name="Postal identification code" type="AN" size="17"/>
    <attribut code="3412" name="Department or employee name" type="AN" size="35"/>
    <attribut code="3413" name="Department or employee name code" type="AN" size="17"/>
    <attribut code="3453" name="Language name code" type="AN" size="3"/>
    <attribut code="4000" name="Reference version identifier" type="AN" size="35"/>
    <attribut code="4078" name="Handling instruction description" type="AN" size="70"/>
    <attribut code="4079" name="Handling instruction description code" type="AN" size="3"/>
    <attribut code="4233" name="Marking instructions code" type="AN" size="3"/>
    <attribut code="4343" name="Response type code" type="AN" size="3"/>
    <attribut code="4440" name="Free text" type="AN" size="512"/>
    <attribut code="4441" name="Free text description code" type="AN" size="17"/>
    <attribut code="4447" name="Free text format code" type="AN" size="3"/>
    <attribut code="4451" name="Text subject code qualifier" type="AN" size="3"/>
    <attribut code="4453" name="Free text function code" type="AN" size="3"/>
    <attribut code="5479" name="Relation code" type="AN" size="3"/>
    <attribut code="6008" name="Height measure" type="N" size="15"/>
    <attribut code="6140" name="Width measure" type="N" size="15"/>
    <attribut code="6145" name="Dimension type code qualifier" type="AN" size="3"/>
    <attribut code="6152" name="Range maximum quantity" type="N" size="18"/>
    <attribut code="6154" name="Non-discrete measurement name" type="AN" size="70"/>
    <attribut code="6155" name="Non-discrete measurement name code" type="AN" size="17"/>
    <attribut code="6162" name="Range minimum quantity" type="N" size="18"/>
    <attribut code="6168" name="Length measure" type="N" size="15"/>
    <attribut code="6245" name="Temperature type code qualifier" type="AN" size="3"/>
    <attribut code="6246" name="Temperature degree" type="N" size="15"/>
    <attribut code="6311" name="Measurement purpose code qualifier" type="AN" size="3"/>
    <attribut code="6313" name="Measured attribute code" type="AN" size="3"/>
    <attribut code="6314" name="Measure" type="AN" size="18"/>
    <attribut code="6321" name="Measurement significance code" type="AN" size="3"/>
    <attribut code="6411" name="Measurement unit code" type="AN" size="8"/>
    <attribut code="6432" name="Significant digits quantity" type="N" size="2"/>
    <attribut code="7064" name="Type of packages" type="AN" size="35"/>
    <attribut code="7065" name="Package type description code" type="AN" size="17"/>
    <attribut code="7088" name="Dangerous goods flashpoint description" type="AN" size="8"/>
    <attribut code="7102" name="Shipping marks description" type="AN" size="35"/>
    <attribut code="7106" name="Shipment flashpoint degree" type="N" size="3"/>
    <attribut code="7124" name="United Nations Dangerous Goods (UNDG) identifier" type="N" size="4"/>
